name: rrclub
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flame: ^1.7.3
  flame_forge2d: ^0.13.0+1
  another_flushbar: ^1.12.30
  carousel_slider: ^4.2.1
  intl: ^0.19.0
  shared_preferences:
  provider: ^6.1.1
  fluttertoast: ^8.2.4
  dio: ^5.4.0
  flutter_widget_from_html:
  flutter_share: ^2.0.0
  url_launcher:
  webview_flutter: 3.0.4
  image_picker: ^1.0.4
  just_audio: ^0.9.36
  audioplayers:
  animated_text_kit: ^4.2.1
  flutter_tawkto: ^0.0.3
  dotted_border: ^2.1.0
  connectivity_plus: ^5.0.2
  url_strategy: ^0.2.0
  share_plus: ^7.2.2
  http:
#  percent_indicator: ^3.0.0
  socket_io_client: ^2.0.3+1
  draggable_fab: ^0.1.4
  add_to_cart_animation: ^2.0.3

  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assetss/images/
    - assetss/images/coin/
    - assetss/images/robot/
    - assetss/images/explosion/
    - assetss/
    - assets/
    - assets/icons/
    - assets/music/
    - assets/images/
    - assets/person/
    - assets/category/
    - assets/aviator/
    - assets/dragontiger/
    - assets/chips/
    - assets/cards/
    - assets/music/dragontiger.mp3


